In [4]:
import pandas as pd
import os

In [22]:
data_file_path = 'C:/Users/lallen1/OneDrive - Thames Water Utilities Limited/Work/Personal/Apprenticeship/Year 1/Term 3 - Data Science Professional Practice/Formative/FPL_player_points_prediction/Data'
files = os.listdir(data_file_path)
historical_data_files = files
historical_data_files.pop(-1)
historical_data_files

['2016-17_merged_gw.csv',
 '2017-18_merged_gw.csv',
 '2018-19_merged_gw.csv',
 '2019-20_merged_gw.csv',
 '2020-21_merged_gw.csv',
 '2021-22_merged_gw.csv',
 '2022-23_merged_gw.csv',
 '2023-24_merged_gw.csv',
 '2024-25_merged_gw.csv']

In [27]:
'''for file in files:
    print(file)'''

file_df = pd.read_csv('C:/Users/lallen1/OneDrive - Thames Water Utilities Limited/Work/Personal/Apprenticeship/Year 1/Term 3 - Data Science Professional Practice/Formative/FPL_player_points_prediction/Data/2016-17_merged_gw.csv',
                      encoding='latin-1')
file_df

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,...,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,GW
0,Aaron_Cresswell,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,55,False,0,0,1
1,Aaron_Lennon,0,3,0,0,0,6,0,1,2,...,0,1,0,0,0,60,True,0,0,1
2,Aaron_Ramsey,0,26,0,0,0,5,0,2,22,...,23,2,0,0,0,80,True,0,0,1
3,Abdoulaye_Doucouré,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,50,False,0,0,1
4,Abdul Rahman_Baba,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,55,True,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23674,Yohan_Cabaye,0,65,0,0,3,42,0,5,57,...,117,10,-2177,152,2329,56,False,0,0,9
23675,Younes_Kaboul,0,34,0,0,0,23,1,7,28,...,12,6,1403,1897,494,44,False,0,0,9
23676,Zlatan_Ibrahimovic,0,40,0,0,0,8,0,4,35,...,56,2,-237262,4227,241489,113,False,0,0,9
23677,Álvaro_Arbeloa,0,0,0,0,0,0,0,0,0,...,0,0,-291,140,431,49,True,0,0,9
23678,Álvaro_Negredo,0,25,0,2,0,-3,1,6,12,...,105,2,-98062,3386,101448,64,False,0,0,9

In [28]:
df = pd.DataFrame()

for file in historical_data_files:
    file_df = pd.read_csv(f'{data_file_path}/{file}',encoding='latin-1')
    df = pd.concat([df, file_df])

df

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,...,expected_goals_conceded,starts,mng_clean_sheets,mng_draw,mng_goals_scored,mng_loss,mng_underdog_draw,mng_underdog_win,mng_win,modified
0,Aaron_Cresswell,0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaron_Lennon,0,3.0,0.0,0.0,0,6,0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aaron_Ramsey,0,26.0,0.0,0.0,0,5,0,2.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdoulaye_Doucouré,0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abdul Rahman_Baba,0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27600,Ashley Young,0,NaN,NaN,NaN,0,23,1,NaN,NaN,...,1.27,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
27601,Somto Boniface,0,NaN,NaN,NaN,0,0,0,NaN,NaN,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
27602,Simon Rusk,0,NaN,NaN,NaN,0,0,0,NaN,NaN,...,0.00,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,False
27603,Arne Slot,0,NaN,NaN,NaN,0,0,0,NaN,NaN,...,0.00,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,False
27604,James Bree,0,NaN,NaN,NaN,0,0,0,NaN,NaN,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False