In [ ]:
# Modules
import pandas as pd
import os

In [13]:
data_file_path = 'C:/Users/lallen1/OneDrive - Thames Water Utilities Limited/Work/Personal/Apprenticeship/Year 1/Term 3 - Data Science Professional Practice/Formative/FPL_player_points_prediction/Data'
files = os.listdir(data_file_path)

# A list of the historical files
historical_data_files = files[:-1]
historical_data_files

['2016-17_merged_gw.csv',
 '2017-18_merged_gw.csv',
 '2018-19_merged_gw.csv',
 '2019-20_merged_gw.csv',
 '2020-21_merged_gw.csv',
 '2021-22_merged_gw.csv',
 '2022-23_merged_gw.csv',
 '2023-24_merged_gw.csv',
 '2024-25_merged_gw.csv']

In [14]:
# Example of one of the dataset 
file_df = pd.read_csv('C:/Users/lallen1/OneDrive - Thames Water Utilities Limited/Work/Personal/Apprenticeship/Year 1/Term 3 - Data Science Professional Practice/Formative/FPL_player_points_prediction/Data/2016-17_merged_gw.csv',
                      encoding='latin-1')
file_df

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,...,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,winning_goals,yellow_cards,GW
0,Aaron_Cresswell,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,55,False,0,0,1
1,Aaron_Lennon,0,3,0,0,0,6,0,1,2,...,0,1,0,0,0,60,True,0,0,1
2,Aaron_Ramsey,0,26,0,0,0,5,0,2,22,...,23,2,0,0,0,80,True,0,0,1
3,Abdoulaye_Doucouré,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,50,False,0,0,1
4,Abdul Rahman_Baba,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,55,True,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23674,Yohan_Cabaye,0,65,0,0,3,42,0,5,57,...,117,10,-2177,152,2329,56,False,0,0,9
23675,Younes_Kaboul,0,34,0,0,0,23,1,7,28,...,12,6,1403,1897,494,44,False,0,0,9
23676,Zlatan_Ibrahimovic,0,40,0,0,0,8,0,4,35,...,56,2,-237262,4227,241489,113,False,0,0,9
23677,Álvaro_Arbeloa,0,0,0,0,0,0,0,0,0,...,0,0,-291,140,431,49,True,0,0,9
23678,Álvaro_Negredo,0,25,0,2,0,-3,1,6,12,...,105,2,-98062,3386,101448,64,False,0,0,9

In [106]:
def caculate_season(df,date_column) -> pd.DataFrame :
    
    # caclulates the season
    year = pd.to_datetime(df[date_column]).dt.strftime('%y')
    year = year.iloc[0]
    season = year + '/' + str(int(year) + 1)
    df['season'] = season
    return df

In [ ]:
# Combines the historical datasets together
historical_df = pd.DataFrame()

for file in historical_data_files:
    file_df = pd.read_csv(f'{data_file_path}/{file}',encoding = 'latin-1')

    # caclulates the season of each file
    caculate_season(file_df,'kickoff_time')

    # Joins the historical datasets into one dataset
    historical_df = pd.concat([historical_df, file_df])

historical_df

,name,assists,attempted_passes,big_chances_created,big_chances_missed,bonus,bps,clean_sheets,clearances_blocks_interceptions,completed_passes,...,expected_goals_conceded,starts,mng_clean_sheets,mng_draw,mng_goals_scored,mng_loss,mng_underdog_draw,mng_underdog_win,mng_win,modified
0,Aaron_Cresswell,0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaron_Lennon,0,3.0,0.0,0.0,0,6,0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aaron_Ramsey,0,26.0,0.0,0.0,0,5,0,2.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdoulaye_Doucouré,0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abdul Rahman_Baba,0,0.0,0.0,0.0,0,0,0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27600,Ashley Young,0,NaN,NaN,NaN,0,23,1,NaN,NaN,...,1.27,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
27601,Somto Boniface,0,NaN,NaN,NaN,0,0,0,NaN,NaN,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
27602,Simon Rusk,0,NaN,NaN,NaN,0,0,0,NaN,NaN,...,0.00,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,False
27603,Arne Slot,0,NaN,NaN,NaN,0,0,0,NaN,NaN,...,0.00,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,False
27604,James Bree,0,NaN,NaN,NaN,0,0,0,NaN,NaN,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False

In [ ]:
# Gets current season data
current_season_data = files[-1]
current_season_df = pd.read_csv(f'{data_file_path}/{current_season_data}',encoding = 'latin-1')
current_season_df = caculate_season(current_season_df,'kickoff_time')
current_season_df

,name,position,team,xP,assists,bonus,bps,clean_sheets,clearances_blocks_interceptions,creativity,...,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,season
0,Reinildo Mandava,DEF,Sunderland,0.5,0,0,27,1,6,2.5,...,0.0,6,0,0,0,40,True,0,1,25/26
1,Lewis Dobbin,MID,Aston Villa,1.0,0,0,0,0,0,0.0,...,0.0,0,0,0,0,50,True,0,1,25/26
2,Ryan Christie,MID,Bournemouth,0.0,0,0,0,0,0,0.0,...,0.0,0,0,0,0,50,False,0,1,25/26
3,Zeki Amdouni,FWD,Burnley,0.0,0,0,0,0,0,0.0,...,0.0,0,0,0,0,50,False,0,1,25/26
4,Lucas Tolentino Coelho de Lima,MID,West Ham,2.6,0,0,11,0,0,14.2,...,4.0,2,0,0,0,60,False,0,1,25/26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18178,Brian Brobbey,FWD,Sunderland,5.0,0,0,3,1,1,12.1,...,21.0,2,92097,110759,18662,56,True,0,24,25/26
18179,Evann Guessand,MID,Aston Villa,0.5,0,0,0,0,0,0.0,...,0.0,0,172,312,140,62,True,0,24,25/26
18180,Kaye Furo,FWD,Brentford,0.0,0,0,0,0,0,0.0,...,0.0,0,168,238,70,45,False,0,24,25/26
18181,Antony dos Santos,MID,Man Utd,0.0,0,0,0,0,0,0.0,...,0.0,0,-14,0,14,59,True,0,24,25/26
18182,Tyler Onyango,MID,Everton,0.0,0,0,0,0,0,0.0,...,0.0,0,-43,0,43,45,False,0,24,25/26

In [133]:
# Combines the historical data of current players with the current seasons data
historical_current_players = historical_df[historical_df['name'].isin(current_season_df['name'])]
combined_df = pd.concat([historical_current_players, current_season_df], ignore_index=True)
combined_df['gw_season'] = ('season_' + combined_df['season'] + '_gw_' + combined_df['GW'].astype(str))

combined_df[['name','GW','season','total_points','gw_season']]

                      name  GW season  total_points           gw_season
0           Aaron Ramsdale   1  20/21             1   season_20/21_gw_1
1             Adam Webster   1  20/21             1   season_20/21_gw_1
2      Alexis Mac Allister   1  20/21             0   season_20/21_gw_1
3               Alex Iwobi   1  20/21             0   season_20/21_gw_1
4          Alphonse Areola   1  20/21             0   season_20/21_gw_1
...                    ...  ..    ...           ...                 ...
71842        Brian Brobbey  24  25/26             2  season_25/26_gw_24
71843       Evann Guessand  24  25/26             0  season_25/26_gw_24
71844            Kaye Furo  24  25/26             0  season_25/26_gw_24
71845    Antony dos Santos  24  25/26             0  season_25/26_gw_24
71846        Tyler Onyango  24  25/26             0  season_25/26_gw_24

[71847 rows x 5 columns]